default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "baka_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "baka_password") %>

development:
  <<: *default
  database: baka_test_summon_development

test:
  <<: *default
  database: baka_test_summon_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_NAME", "baka_test_summon_production") %>
