#!/usr/bin/env bash

set -u
printf 'curl %s\n' "$*" >>"$FAKE_COMMAND_LOG"

if [[ -n "${FAKE_HEALTH_SEQUENCE:-}" ]]; then
  IFS=',' read -r -a statuses <<<"$FAKE_HEALTH_SEQUENCE"
  counter=0
  if [[ -f "$FAKE_HEALTH_COUNTER" ]]; then
    counter=$(cat "$FAKE_HEALTH_COUNTER")
  fi
  status_index=$counter
  if ((status_index >= ${#statuses[@]})); then
    status_index=$((${#statuses[@]} - 1))
  fi
  printf '%d\n' "$((counter + 1))" >"$FAKE_HEALTH_COUNTER"
  exit "${statuses[$status_index]}"
fi

exit "${FAKE_HEALTH_STATUS:-0}"
