#!/usr/bin/env bash

set -u
printf 'systemctl %s\n' "$*" >>"$FAKE_COMMAND_LOG"

if [[ "$*" == "--user restart "* && -n "${FAKE_SYSTEMCTL_RESTART_SEQUENCE:-}" ]]; then
  IFS=',' read -r -a statuses <<<"$FAKE_SYSTEMCTL_RESTART_SEQUENCE"
  counter=0
  if [[ -f "$FAKE_SYSTEMCTL_COUNTER" ]]; then
    counter=$(cat "$FAKE_SYSTEMCTL_COUNTER")
  fi
  status_index=$counter
  if ((status_index >= ${#statuses[@]})); then
    status_index=$((${#statuses[@]} - 1))
  fi
  printf '%d\n' "$((counter + 1))" >"$FAKE_SYSTEMCTL_COUNTER"
  exit "${statuses[$status_index]}"
fi
